#spring:
#    security:
#        user:
#            name: user
#            password: password


spring:
    h2:
        console:
            enabled: true
            path: /h2-console

jdbc:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/data/security;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    user: sa
    pass:
